# Generated by Django 5.2.4 on 2025-07-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='album_fotos/')),
                ('legenda', models.CharField(blank=True, max_length=100, null=True)),
                ('data_adicionada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
