# Generated by Django 5.2.4 on 2025-07-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossa_historia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('duracao', models.CharField(blank=True, help_text='Formato: MM:SS', max_length=10)),
                ('letra', models.TextField(blank=True)),
                ('capa', models.ImageField(help_text='Capa do álbum ou single', upload_to='capas_musicas/')),
                ('arquivo_mp3', models.FileField(blank=True, help_text='Faça upload de um arquivo MP3', null=True, upload_to='musicas_mp3/')),
                ('link_youtube', models.URLField(blank=True, help_text='Cole o link do YouTube aqui', null=True)),
                ('data_adicionada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_adicionada'],
            },
        ),
    ]
