# Generated by Django 5.2.4 on 2025-07-31 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossa_historia', '0002_musica'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='data_foto',
            field=models.DateField(default=django.utils.timezone.now, help_text='A data em que a foto foi tirada.'),
        ),
    ]
